set("CONFIG_MACRO" "BOOST_REGEX_MATCH_EXTRA" CACHE INTERNAL "")
set("CONFIG_MACRO" "${CONFIG_MACRO}" "BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS" CACHE INTERNAL "")
set("CONFIG_MACRO_BOOST_MPL_LIMIT_LIST_SIZE" "3" CACHE INTERNAL "")
