set("DEPENDS_ON_PACKAGES" "glib" CACHE INTERNAL "")
set("DEPENDS_ON_PKGCONFIGS" "glib-2.0" CACHE INTERNAL "")
set("PKGCONFIG_EXPORT_TARGETS" "gstreamer-1.0" CACHE INTERNAL "")
set("BUILD_SHARED_LIBS" "ON" CACHE INTERNAL "")
