set("LLVM_INCLUDE_EXAMPLES" "OFF" CACHE INTERNAL "")
set("LLVM_INCLUDE_TESTS" "OFF" CACHE INTERNAL "")
set("LLVM_INCLUDE_DOCS" "OFF" CACHE INTERNAL "")
set("LLVM_BUILD_EXTERNAL_COMPILER_RT" "ON" CACHE INTERNAL "")
