set("DEPENDS_ON_PACKAGES" "pip_lazy-object-proxy" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "pip_wrapt" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "pip_six" CACHE INTERNAL "")
