set("DEPENDS_ON_PACKAGES" "xproto" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "xtrans" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "ice" CACHE INTERNAL "")
