set("DEPENDS_ON_PACKAGES" "pip_certifi" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "pip_chardet" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "pip_idna" CACHE INTERNAL "")
set("DEPENDS_ON_PACKAGES" "${DEPENDS_ON_PACKAGES}" "pip_urllib3" CACHE INTERNAL "")
