set("PKGCONFIG_EXPORT_TARGETS" "libpcre" CACHE INTERNAL "")
set("PKGCONFIG_EXPORT_TARGETS" "${PKGCONFIG_EXPORT_TARGETS}" "libpcrecpp" CACHE INTERNAL "")
set("PKGCONFIG_EXPORT_TARGETS" "${PKGCONFIG_EXPORT_TARGETS}" "libpcreposix" CACHE INTERNAL "")
set("EXTRA_FLAGS" "--enable-unicode-properties" CACHE INTERNAL "")
